# Generated by Django 3.2.4 on 2021-06-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
